/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Shapes;
import com.github.cliftonlabs.json_simple.JsonArray;
import com.github.cliftonlabs.json_simple.JsonException;
import com.github.cliftonlabs.json_simple.JsonObject;
import com.github.cliftonlabs.json_simple.Jsoner;
import java.awt.*;  
import javax.swing.JFrame;
import java.awt.Graphics;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Point; 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
/**
 *
 * @author zedan.net
 */
public class Paint extends javax.swing.JFrame implements  Node {
  private static int lcounter =1 ;
  private static int rcounter =1 ;
  private static int scounter =1 ;
  private static int ccounter =1 ;
  private static int tcounter =1 ;
  private CircleGui c ;  
  private RectangleGui r ;
  private SegmentGui l;
  private TriangleGui t ;
    /**
     * Creates new form draw
     */
    public Paint() {
        initComponents();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        mypanel1 = new Shapes.Mypanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Line Segment ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rectangle ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Oval");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Shapes");

        jButton5.setText("Set border color");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose shape" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        mypanel1.setBackground(new java.awt.Color(255, 255, 255));
        mypanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mypanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mypanel1MouseDragged(evt);
            }
        });
        mypanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mypanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mypanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout mypanel1Layout = new javax.swing.GroupLayout(mypanel1);
        mypanel1.setLayout(mypanel1Layout);
        mypanel1Layout.setHorizontalGroup(
            mypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        mypanel1Layout.setVerticalGroup(
            mypanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        jButton7.setText("Set fill color");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Triangle");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setText("Copy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Save as");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Load");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mypanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(mypanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


       if(l == null)
       {
           l = new SegmentGui(this);
           l.setTitle("LineSegment Gui");
       }
       l.setParentNode(this);
       this.setVisible(false);
       l.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      if(r == null)
      {
          r = new RectangleGui(this);
          r.setTitle("Rectangle data");
      }
                    r.setParentNode(this);
                    this.setVisible(false);
                    r.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          

      if(c == null)
      {
          c = new CircleGui(this);
          c.setTitle("Circle Data");
      }
      this.setVisible(false);
      c.setParentNode(this);
      c.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public void adder ( Shape s , String ss)
    {
                
    mypanel1.addShape(s);
    mypanel1.refresh(null);
    if(ss.equals("circle")){
        jComboBox1.addItem("Oval_"+ccounter);
       ccounter++;
    }
    if(ss.equals("Rectangle")){
        jComboBox1.addItem("Rectangle_ "+rcounter);
    rcounter++;
    }
    if(ss.equals("line")){
        jComboBox1.addItem("LineSegment_"+lcounter);
    lcounter++;
    }
   
    if(ss.equals("Triangle")){
        jComboBox1.addItem("Triangle_"+tcounter);
    tcounter++;
    }
    }
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       if (jComboBox1.getSelectedIndex() > 0) {
            Color chosenColor = JColorChooser.showDialog(null, "Select a color", Color.white);
           
            
          mypanel1.getter().get(jComboBox1.getSelectedIndex()-1 ).setColor(chosenColor);
          mypanel1.refresh(null);
        }
        else 
            JOptionPane.showMessageDialog(this,"Nothing to colorize ","NO SHAPES",JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         if (jComboBox1.getSelectedIndex() > 0) {
            Color chosenFillColor = JColorChooser.showDialog(null, "Select a color", Color.white);
           
            
            mypanel1.getter().get(jComboBox1.getSelectedIndex()-1 ).setFillColor(chosenFillColor);
          mypanel1.refresh(null);
        }
        else 
            JOptionPane.showMessageDialog(this,"Nothing to colorize ","NO SHAPES",JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          if (jComboBox1.getSelectedIndex() > 0) {
              Shape shape = mypanel1.getter().get(jComboBox1.getSelectedIndex()-1);
              mypanel1.removeShape(shape);
              mypanel1.refresh(null);
              jComboBox1.removeItemAt(jComboBox1.getSelectedIndex());
          }
              else 
            JOptionPane.showMessageDialog(this,"Nothing to delete  ","NO SHAPES",JOptionPane.INFORMATION_MESSAGE);
          
          for(Shape s : mypanel1.getter())
          {   
              System.out.println(s.getColor());
          }
          System.out.println("------------------------------------------------------------------------------------");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(t == null)
      {
          t = new TriangleGui(this);
          t.setTitle("Triangle Data");
      }
      this.setVisible(false);
      t.setParentNode(this);
      t.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void mypanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mypanel1MouseClicked
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(mypanel1.getComboIndex());
    }//GEN-LAST:event_mypanel1MouseClicked

    private void mypanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mypanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_mypanel1MouseDragged

    private void mypanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mypanel1MousePressed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(mypanel1.getComboIndex());
    }//GEN-LAST:event_mypanel1MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if((jComboBox1.getSelectedIndex()-1)>=0)
{
  Shape s = mypanel1.getter().get(jComboBox1.getSelectedIndex()-1);
      
         Paint d = this;

     if( s instanceof Rectangle)
     {
         System.out.println("In rect ya migzooo");
         Rectangle newRect = new Rectangle(0,0,null);
         Point refrence =new Point(s.getPosition().x,s.getPosition().y);
         int lengthOfRect = ((Rectangle)s).getLength();
         int widthOfRect = ((Rectangle)s).getWidth();
         newRect.setPosition(refrence);
         newRect.setLength(lengthOfRect);
         newRect.setWidth(widthOfRect);
         newRect.setColor(s.getColor());
         newRect.setFillColor(s.getFillColor());
         d.adder(newRect, "Rectangle");
        newRect = new Rectangle(0,0,null);  
            }
      if(s instanceof Triangle)
      {
          
         
          System.out.println("In tri ya megzoo");
          Triangle t = new Triangle(null, null,null);
          Point ref = new Point(s.getPosition().x,s.getPosition().y);
          Point ref2 = new Point(((Triangle)s).getPoint2().x ,((Triangle)s).getPoint2().y);
          Point ref3 = new Point(((Triangle)s).getPoint3().x,((Triangle)s).getPoint3().y) ; 
          t.setPosition(ref);
          t.setPoint2(ref2);
          t.setPoint3(ref3);
          t.setColor(s.getColor());
          t.setFillColor(s.getFillColor());
          d.adder(t,"Triangle");
          t = new Triangle(null, null,null);
          }
        if(s instanceof LineSegment)
        {
            LineSegment newline = new LineSegment(null,null);
            Point l1 = new Point(s.getPosition().x,s.getPosition().y);
            Point l2 = new Point (((LineSegment)s).getPosition2().x,((LineSegment)s).getPosition2().y);
            newline.setPosition(l1);
            newline.setPosition2(l2);
            newline.setColor(s.getColor());
            d.adder(newline, "line");
            newline = new LineSegment(null,null);
       }
        if(s instanceof Circle)
        {
            Circle circle = new Circle(null,0,0);
            Point centerpoint = new Point (s.getPosition().x,s.getPosition().y);
            int vr = ((Circle)s).getLength();
            int hrr = ((Circle)s).getWidth();
            circle.setPosition(centerpoint);
            circle.setWidth(hrr);
            circle.setLength(vr);
            circle.setColor(s.getColor());
            circle.setFillColor(s.getFillColor());
            d.adder(circle,"circle");
            circle = new Circle(null,0,0);
            
        }
}
else
{
    JOptionPane.showMessageDialog(null, "You Have not chosen a shape yet to copy ");
}
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
                JFileChooser filechooser = new JFileChooser();
       
        int response = filechooser.showSaveDialog(this);

        if(response == JFileChooser.APPROVE_OPTION)
        {
            
            String path=filechooser.getSelectedFile().getAbsolutePath();
            JsonArray ja=new JsonArray();
            for(Shape shape: mypanel1.getter())
            {
                ja.add(shape.toJsonObject());
            }
            String jsontext = Jsoner.serialize(ja);
            OutputStream os = null;
        try {
            os = new FileOutputStream(new File(path));
            os.write(jsontext.getBytes(), 0, jsontext.length());
            os.close();
            System.out.println("File saved");
        } catch (IOException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        int response = filechooser.showOpenDialog(this);
        if(response == JFileChooser.APPROVE_OPTION)
        {
            lcounter =1 ;
            rcounter =1 ;
            ccounter =1 ;
            tcounter=1;
            
            JsonArray ja = null;
           mypanel1.getter().clear();
           jComboBox1.removeAllItems();
            jComboBox1.addItem("Choose shape");
            String path = filechooser.getSelectedFile().getAbsolutePath();
            File file = new File(path);
            FileInputStream fileInputStream = null;
            byte[] bFile = new byte[(int) file.length()];
            try {
                fileInputStream = new FileInputStream(file);
                fileInputStream.read(bFile);
                fileInputStream.close();
            
            String jsontext = new String(bFile);
            
                try {
                    ja = (JsonArray) Jsoner.deserialize(jsontext); 
                } catch (JsonException ex) {
                    Logger.getLogger(Paint.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Paint.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Paint.class.getName()).log(Level.SEVERE, null, ex);
            }
           // System.out.println(ja.size());
            for(Object object : ja)
            {
           
                JsonObject jo=(JsonObject) object;
                String type = (String)jo.get("Type");
                if(type.contains("Triangle"))
                {
                    System.out.println("in t if");
                    Shape t = new Triangle(null, null, null);
                    t.fromJsonObject(jo);
                    adder(t,"Triangle");
                    
                }
                if(type.contains("Rectangle"))
                {
                    System.out.println("in r if");
                    Shape r=new Rectangle(0, 0, null);
                    r.fromJsonObject(jo);
                    adder(r,"Rectangle");
                }
                if(type.contains("Oval"))
                {
                    System.out.println("in o if");
                    Shape o=new Circle(null, 0,0);
                    o.fromJsonObject(jo);
                    adder(o,"circle");
                }
                if(type.contains("Line"))
                {
                    System.out.println("in l if");
                    Shape l=new LineSegment(null, null);
                    l.fromJsonObject(jo);
                    adder(l,"line");
                }
            }
            
            
           
            
            
        }
        mypanel1.refresh(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

       

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Paint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private Shapes.Mypanel mypanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNode(Node node) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Node getParentNode() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
}
